# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        args: ["--fix", "--unsafe-fixes"] # <--- ADD --unsafe-fixes
      - id: ruff-format

  